baseURL = "https://nullnotes.netlify.com"
languageCode = "en-us"
title = "Null Notes"
theme = "flex"

[params]
    # mainSections = ["posts", "quotes"]
    mainSections = ["posts"]

[permalinks]
    posts = "/:year/:month/:title/"
    quotes = "/:year/:month/:title/"