# Favicon
favicon: /favicon.ico

# SEO
keywords: Computer Science, Language Learning, Video Games, Learning Method, Book Review.

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/nullenemy
  # V2EX: https://www.v2ex.com/member/chunqiuyiyu

# Nav menu
menu:
  Home: /
  Archives: /archives
  # About: /about